import type { RuntimeConfig } from 'nuxt/schema'
import { OAuth2Client } from 'google-auth-library'
import { google } from 'googleapis'

import type { IGmailApiService } from '~/server/interfaces/services'
import {
  GetCurrentAuthError,
  ApiSendEmailError, GetNewCredentialsError, InitializeGmailError, OAuthInitializationError,
} from '~/server/errors/custom-errors'

export class GmailApiService implements IGmailApiService {
  private oauth2: OAuth2Client | undefined
  private config: RuntimeConfig

  constructor() {
    this.config = useRuntimeConfig()
  }

  private _ensureAuthInitialized(): OAuth2Client {
    if (!this.oauth2) {
      this.newAuth()
    }
    return this.oauth2!
  }

  /**
   * Prepare the OAuthClient with credentials from .env and
   * generated from Google Cloud
   */
  newAuth() {
    try {
      this.oauth2 = new OAuth2Client(
        this.config.private.clientID,
        this.config.private.clientSecret,
        this.config.private.redirectUri,
      )
    }
    catch (e) {
      throw new OAuthInitializationError(`Error initializing OAuth2Client: ${(e as Error).message}`)
    }
  }

  /**
   * Before send email
   * @private
   */
  async initializeGmail() {
    if (this.oauth2) {
      return google.gmail({
        version: 'v1',
        auth: this.oauth2,
      })
    }
    throw new InitializeGmailError('OAuth2Client is not initialized')
  }

  /**
   * Generate the OAuth identification link used for generating a code
   * used to receive the refresh_token
   */
  async getAuthUrl(): Promise<string> {
    const auth = this.getAuth()
    return auth.generateAuthUrl({
      access_type: 'offline',
      prompt: 'consent',
      scope: [this.config.private.apiScope],
    })
  }

  /**
   * Enable first refresh_token with the code generated by the identification URL
   * @param code
   */
  async getFirstAccessToken(code: string) {
    try {
      // If first connection with code received by getUrl
      const auth = this.getAuth()
      const { tokens } = await auth.getToken(code)
      console.log('TOKENS =>', tokens)
      return tokens
    }
    catch (error) {
      console.error('Error retrieving access token', error)
      return undefined
    }
  }

  /**
   * Recovering new credentials with google-auth libraries
   * @param refreshToken
   */
  async getNewCredentials(refreshToken: string) {
    const auth = this._ensureAuthInitialized()

    // Definition of identification information
    auth.setCredentials({ refresh_token: refreshToken })

    try {
      const { credentials } = await auth.refreshAccessToken()

      if (!credentials) {
        throw new GetNewCredentialsError('No token provided')
      }

      return credentials
    }
    catch (error) {
      throw new GetNewCredentialsError(error instanceof Error ? error.message : 'Unknown error')
    }
  }

  /**
   * Return the current OAuth client
   */
  getAuth() {
    if (this.oauth2) {
      return this.oauth2
    }
    throw new GetCurrentAuthError('OAuth2 client is not defined !')
  }

  /**
   * Send the email by the Google Gmail API
   * @param encodedEmail
   * @param access_token
   */
  async send(encodedEmail: string, access_token: string) {
    const auth = this._ensureAuthInitialized()

    auth.setCredentials({ access_token })

    const gmail = await this.initializeGmail()

    try {
      const response = await gmail.users.messages.send({
        userId: 'me',
        requestBody: { raw: encodedEmail },
      })
      return { success: true, message: `Email successfully sent, Date => ${response.data.internalDate}` }
    }
    catch (err) {
      throw new ApiSendEmailError(`API returned an error: ${(err as Error).message}`, { error: err })
    }
  }
}
